### PR TITLE
Added header tailormap-username so the called service knows who sends it

### PR DESCRIPTION
**Pull request by mtoonen**

### CODE REVIEW

**Review by matthijsln — COMMENTED** [review]
I assume this header is meant so endpoints (such as feature-api) can check layer/featuretype authorizations.

Currently only authenticated users are allowed access to proxied backends so the header never has a 'null' value. What about configuring endpoints in the database and allowing access for everyone, all authenticated users, users in group(s)?

**Comment by mtoonen** [comment]
> I assume this header is meant so endpoints (such as feature-api) can check layer/featuretype authorizations.
> 
> Currently only authenticated users are allowed access to proxied backends so the header never has a 'null' value. What about configuring endpoints in the database and allowing access for everyone, all authenticated users, users in group(s)?

This is used in a different API, which stories the user making the request. That API has no principal, so no access to the username.

**Comment by matthijsln** [comment]
> > I assume this header is meant so endpoints (such as feature-api) can check layer/featuretype authorizations.
> > Currently only authenticated users are allowed access to proxied backends so the header never has a 'null' value. What about configuring endpoints in the database and allowing access for everyone, all authenticated users, users in group(s)?
> 
> This is used in a different API, which stories the user making the request. That API has no principal, so no access to the username.

Hence the use of _such as_ :) In the future backend for other purposes may need more fine-grained access control, but that and database config can be added later. As mentioned in #2778, this header is usually called `X-Remote-User` or `X-Forwarded-User` for proxies specifically.

**Comment by matthijsln** [comment]
> > > I assume this header is meant so endpoints (such as feature-api) can check layer/featuretype authorizations.
> > > Currently only authenticated users are allowed access to proxied backends so the header never has a 'null' value. What about configuring endpoints in the database and allowing access for everyone, all authenticated users, users in group(s)?
> > 
> > 
> > This is used in a different API, which stories the user making the request. That API has no principal, so no access to the username.
> 
> Hence the use of _such as_ :) In the future backend for other purposes may need more fine-grained access control, but that and database config can be added later. As mentioned in #2778, this header is usually called `X-Remote-User` or `X-Forwarded-User` for proxies specifically.

**Comment by mtoonen** [comment]
superseded by #2778

**Pull request closed without merging**
