### PR TITLE
PDOK changed their URL's

### PR DESCRIPTION
**Pull request by mvdstruijk**

### CODE REVIEW

**Review by mprins — CHANGES_REQUESTED** [review]
Not the same service, there is/was a reason for using the INSPIRE service.

Use https://service.pdok.nl/kadaster/au/wms/v2_0?request=GetCapabilities&service=WMS

see https://www.pdok.nl/-/wijziging-administratieve-eenheden-inspire-geharmoniseerd-

**Comment by mprins** [comment]
should also be backported to stable branches

**Review by mprins — APPROVED** [review]

**Comment by mprins** [comment]
@mvdstruijk Automatic backports failed, you'll need to do this manually

**Comment by mvdstruijk** [comment]
@mprins Yes i see.
What should we do with the PR's that are made from dependabot? All these PR's failed due to the failing test.

**Comment by mprins** [comment]
add comment `@dependabot rebase`...

gnome-shell-screenshot-29WIG1

**Pull request merged**
