### PR TITLE
Upgrade to GeoTools 20

### PR DESCRIPTION
**Pull request by mprins**
- [x] GeoTools 20-RC and required JTS changes
- [x] GeoTools 20.0
- [x] datasotelinker-bom update (B3Partners/datastorelinker-bom#12)
- [x] b3p-commons-csw upgrade (B3Partners/b3p-commons-csw#17)

see: http://docs.geotools.org/latest/userguide/welcome/upgrade.html#geotools-20-x

### CODE REVIEW

**Comment by mprins** [comment]
Some test failing, maybe due to the UoM changes in GT20

failing tests
```
[ERROR]   TileServiceTest.testLoadArcGisWMTSFromURL:151 expected:<-7191.98> but was:<-7170.541405236814>
[ERROR]   TileServiceTest.testLoadBRTWMTSFromURL:110 expected:<595323.04> but was:<595401.920067406>
```

`TileServiceTest.testLoadArcGisWMTSFromURL` uses capabilities with the following:
```xml
<Contents>
    <Layer>
        <ows:Title>Historische_tijdreis_1950</ows:Title>
        <ows:Identifier>Historische_tijdreis_1950</ows:Identifier>
        <ows:BoundingBox crs="urn:ogc:def:crs:EPSG::28992">
            <ows:LowerCorner>-1280.7604000009596 -5049.074299998581</ows:LowerCorner>
            <ows:UpperCorner>293512.95708775596 659829.9918000016</ows:UpperCorner>
        </ows:BoundingBox>
        <ows:WGS84BoundingBox crs="urn:ogc:def:crs:OGC:2:84">
            <ows:LowerCorner>3.009687194217067 47.929606189538354</ows:LowerCorner>
            <ows:UpperCorner>7.494617901300302 53.92386074950479</ows:UpperCorner>
        </ows:WGS84BoundingBox>
        <Style isDefault="true">
```

`TileServiceTest.testLoadBRTWMTSFromURL` uses capabilities with the following:

```xml
<Contents>
    <Layer>
        <ows:Title>brtachtergrondkaart</ows:Title>
        <ows:WGS84BoundingBox>
            <ows:LowerCorner>-1.65729160235431 48.0405018704265</ows:LowerCorner>
            <ows:UpperCorner>11.2902578747914 55.9136415748388</ows:UpperCorner>
        </ows:WGS84BoundingBox>
        <ows:Identifier>brtachtergrondkaart</ows:Identifier>
        <Style isDefault="true">
```

@mtoonen Any idea?

**Comment by mprins** [comment]
latest test results
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TileServiceTest.testLoadArcGisWMTSFromURL:151 expected:<-7191.98> but was:<-7170.541405236814>
[ERROR]   TileServiceTest.testLoadBRTWMTSFromURL:110 expected:<595323.04> but was:<595401.920067406>
[INFO] 
```

https://travis-ci.org/flamingo-geocms/flamingo/jobs/432880131#L2893-L2894

**Comment by mprins** [comment]
I have adjusted the expected bbox corner values, but these will need to be validated visually I guess with eg. a WMS

**Review by mtoonen — APPROVED** [review]

**Comment by mprins** [comment]
rebase to master, force pushed.

I tested with pdok wmts + wms from different server, railsroads line up:
image
Also checked with wms aerial imagery

**Pull request merged**
