### PR TITLE
Pass the layers as well as the store in the ON_LAYERSELECTOR_INITLAYERS

### LINKED ISSUE #51: Bewerken link is alleen zichtbaar in de feature-info als kaartlaag in het startkaartbeeld staat
beschrijving in Mantis: http://mantis.b3p.nl/view.php?id=5960

### LINKED ISSUE #654: edit link of feature info only available for active layers
### Where?
viewer, featureinfo component + edit component

### What happened
the edit link is not available for layers that were not active during control initialization

### What did you expect?
For any editable layer the link should be present if the layer is visible

### Version
4.7.4

### PR DESCRIPTION
**Pull request by mprins**
This will make it possible to get a handle on all layers of the layerselector, eg all eeditable layers instead of just the vidisible editable layers.

This will allow the Edit control to register all editable layers with the FeatureInfo control and not just the visisble editable layers.

close #654
close B3Partners/flamingo-ibis#51

### CODE REVIEW

**Comment by mprins** [comment]
close http://mantis.b3p.nl/view.php?id=5960

**Comment by mtoonen** [comment]
Wasn't this event caught by other components as well? Should we change them
too?

**Comment by mprins** [comment]
None of the other components seems to use the passed data, mostly the event is used to set the dropdown to first item.

**Comment by mtoonen** [comment]
Oh, you're right. My bad.

**Pull request merged**
