### PR TITLE
Fix Oracle syntax error in upgrade script

### PR DESCRIPTION
**Pull request by mprins**

### CODE REVIEW

**Review by mtoonen — APPROVED** [review]
Oooo, thats why upgrades failed... Thanks!

**Comment by mprins** [comment]
thanks @BaderAhmad

**Comment by mprins** [comment]
I think maybe we should set up automated testing for schema upgrades. Did something similar for https://github.com/B3Partners/brmo

**Comment by mprins** [comment]
does not exist in v5.4.x

**Pull request merged**
